spring:
  application:
    name: mailer-service
  mail:
    port: 2525
    username: 439c0d3cabf11b
    password: c6f2aa5c231235
    protocol: smtp
    default-encoding: UTF-8
    host: smtp.mailtrap.io
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          lob:
#            non_contextual_creation: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ci-settings
#    username: postgres
#    password: 123


server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# Auth JWT
jwt:
  header: Authorization
  secret: quebic_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh
